services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - goal_db_data:/data
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always


volumes:
  goal_db_data: