[pytest]
filterwarnings =
    ignore:.*TestClient.*:DeprecationWarning
    ignore:.*BlockingPortal.*:DeprecationWarning
    ignore:.*httpx.*:UserWarning
    ignore::DeprecationWarning:starlette
    ignore::DeprecationWarning:anyio
